name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: [push]
env:
  WORKFLOW_MESSAGE: 'Hello from the workflow environment!'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          echo "---Current working dir---"
          pwd
      - name: Dump environment1
        run: |
          env | sort
      # - name: Dump /github files
      #   run: |
      #     find /github -print
      - name: Set output
        run: |-
          echo myOutput=myOutputValue >> $GITHUB_OUTPUT
          echo MYENV=myEnvValue >> $GITHUB_ENV
          echo "$HOME/.custom-path/bin" >> $GITHUB_PATH
          echo "example_1 Added some variables" >> $GITHUB_STEP_SUMMARY
      - name: Dump environment2
        run: |
          env | sort
      - name: Action dump
        uses: swashbuck1r/docker-action-dump@v1
        with:
          go-version: "1.18"
      - name: Dump /home files
        run: |
          ls -al /home
          # find /home -print
      - name: Write /tmp/goo file
        run: echo "hello goo" > /tmp/goo
      - name: List /tmp/goo file
        run: ls -al /tmp/goo
      - run: echo "üçè This job's status is ${{ job.status }}."
  say_hello_from_env:
    runs-on: ubuntu-latest
    env:
      JOB_MESSAGE: 'Hello from the job environment!'
    steps:
      - name: Say hello based on workflow env
        run: echo "$WORKFLOW_MESSAGE"
      - name: Say hello based on job env
        run: echo "$JOB_MESSAGE"
      - name: Say hello based step env
        run: echo "$STEP_MESSAGE"
        env:
          STEP_MESSAGE: 'Hello from the step environment!'

